### ISSUE TITLE
Kuro Playground で README のサンプルがエラー

### ISSUE THREAD

**Issue by Reputeless** [quro-framework/kuro-lang#3]
- Tax calculation
- Browser & Fetch API

ともにエラーで実行できません。

**Comment by yasulab** [comment]
ちなみにこんな感じですね。[`use` トークン自体は用意されてそう](https://github.com/kuro-lang/kuro-lang/search?q=use)だけど、Parser 側もしくはブラウザ版だと未対応って感じなのかな...? 🤔💭

![image](https://user-images.githubusercontent.com/155807/116505607-4a7c1880-a8f6-11eb-8664-ca131bcb2d01.png)

**Comment by hota1024** [comment]
issueありがとうございます！気づくのが遅れてしまい申し訳ないです🙏
@yasulab さんの仰るとおり `use` はトークンのみ対応して、現在裏でモジュールの仕組みを設計している状況です。
動かないコードをサンプルとして置いておくのは不適切でした。修正しておきます。
